### PR TITLE
Added onQueue and onLater functions

### LINKED ISSUE #14: Mail queue/later methods
Laravel Mail has the following functions in the mail docs:
* queueOn
* laterOn

How do you feel about adding these methods within Mailthief?

### PR DESCRIPTION
**Pull request by michaelachrisco**
Closes #14

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Let me know if you want specific test coverage on these methods.

**Comment by mattstauffer** [comment]
The docs show `queueOn` and `laterOn`, not `onQueue` and `onLater`.

W/r/t test coverage, I'd say yes: If we can test that the correctly pass their params on, that'd be enough.

Thanks!

**Comment by michaelachrisco** [comment]
Oops you are correct. I was looking at the mail file for the onQueue method. https://github.com/laravel/framework/blob/5.2/src/Illuminate/Mail/Mailer.php#L215

Looks like there is the documented `queueOn` and 'laterOn` methods as well as the undocumented `onQueue` method.

**Comment by besologic** [comment]
@michaelachrisco Thanks for the contribution! Wanted to check in, are you planning on adding tests for this?

**Comment by michaelachrisco** [comment]
Apologies! I have been swamped at work. Yes plan on committing some tests when I get the time.

**Comment by besologic** [comment]
No problem at all, just making sure 👍

**Comment by besologic** [comment]
@michaelachrisco Thanks again for your work on this. I had some time today so I went ahead and added the tests in #45.

**Pull request closed without merging**
