### PR TITLE
Fix the error of missing addPart method

### PR DESCRIPTION
**Pull request by T3chn0crat**
This will fix issue #8 where a missing method addPart can happen with attempting to add message parts like content types.

### CODE REVIEW

**Comment by besologic** [comment]
@T3chn0crat, can you add a comment in the method with an explanation of why its there and empty?

At some point we probably may want to support checking for content types and we would need to actually implement this.

**Comment by T3chn0crat** [comment]
Because I do not see a real reason to test it off hand.  Most people are going to want to test simply the message, to, from, etc and probably not something as trivial as the content types.  But I could change that.

However I just ran into another method that is missing.  Probably better to do something less brittle than just adding the empty methods for all the SwiftMailer message class has.  Maybe do something more with __call and running it through the local method, if not found check it against what is callable in the real class (some how), and if it exists just take it in and return true for now.  Or maybe add a wasCalled or something to validate.

**Comment by T3chn0crat** [comment]
So I have been trying to figure out an elegant solution to this problem and I am not sure there is one.  There are so many different possible methods that could be called that it's almost impossible unless we try to fake them all which seems needless.  Maybe it would be better to just return $this in the __call method.  It will stop the errors on these calls.

**Comment by mattstauffer** [comment]
that's an interesting idea. Just swallow non-supported methods, assuming they're all intending to be passed to swiftmailer?

**Comment by T3chn0crat** [comment]
@mattstauffer Correct.  I really do not see a better option.  That way any test will "pass".  

So something like:
```php
    public function __call($name, $arguments)
    {
        return $this;
    }
```

I am not sure if anyone really cares if like the addPart method gets called or not.  Really what does it show?  I think the most important results are covered.

This would allow anyone that does want to stub out methods later to do so.

**Comment by mattstauffer** [comment]
@T3chn0crat I think that's a really good idea. Would you mind PR-ing that, and maybe write a few tests to show that a few basic SwiftMailer calls can be called without error, so we can use those tests to describe why that `__call` is there?

**Comment by T3chn0crat** [comment]
Superseded by pull #36

**Pull request closed without merging**
