### PR TITLE
Added a bit of type checking around potentially null parameters

### PR DESCRIPTION
**Pull request by assertchris**
...Also added php ^7.0 as a dev requirement, since the tests require anonymous classes.

### CODE REVIEW

**Comment by ksassnowski** [comment]
The problem is, that the `$callback` parameter doesn't have to be a Closure. It can also be a string, in which case it will try to resolve it out of the IoC container and call the `mail` method on it as seen [here](https://github.com/illuminate/mail/blob/master/Mailer.php#L406).

So while I agree that the implementation is incomplete this pull request doesn't really solve the problem. It would simply suppress an exception if the `$callback` parameter is not of the correct type.

**Comment by assertchris** [comment]
@ksassnowski the way `$callback` is used requires it to be callable. I think this is a good first step on the road to an exception-free implementation...

**Comment by ksassnowski** [comment]
> the way `$callback` is used requires it to be callable.

Not in the actual `Mailer` implementation I linked above. You could also provide a container alias, which is simply a string. No need for it to be callable.

> I think this is a good first step on the road to an exception-free implementation...

The actual `Mailer` throws an exception if the callback is invalid [https://github.com/illuminate/mail/blob/master/Mailer.php#L410](https://github.com/illuminate/mail/blob/master/Mailer.php#L410). So we don't want an exception-free implementation since that would mean that the test would behave differently than the actual production code. It should throw the same Exception under the same circumstances as the actual `Mailer` class.

**Comment by mattstauffer** [comment]
If I'm reading the PR and the linked mailer class correctly, our better fix would be to reproduce the Mailer's `callMessageBuilder` method so that we can be in better parity, allowing both strings and Closures and throwing exceptions if neither work?

**Comment by assertchris** [comment]
Indeed, @ksassnowski's suggestions would be the best approach I think.

**Pull request closed without merging**
