### PR TITLE
[Bugfix] Laravel 5.5 Compatibility

### PR DESCRIPTION
**Pull request by wells**
This pull request resolves issues with the latest commit to support Laravel 5.5. 

Please reference the most recent comments in Issue #76 to see a detailed explanation on how this fixes the current release for laravel v5.5.

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks a bunch for this @wells

**Comment by wells** [comment]
No worries 👍

**Comment by tobiasdierich** [comment]
I've just installed the latest dev-master version in my app and got this exception:
```
Error: Call to a member function version() on null
```

I'm pretty sure this is caused by the `hijackMail()` method trying to access the `$app` instance which is only available after `setUp()` has been called, however, `hijackMail()` runs before `setUp()`.

**Comment by wells** [comment]
@tobiasdierich Tricky. I didn't run into this when I was testing this out on laravel 5.5. Yeah, it looks like `createApplication()` is called at the start of the `setup()` function. And because of the breaking change in phpunit 6, it can't be accessible from older versions of phpunit. Hmm...

@calebporzio I will need to remove the version check at `hijackMail()`, given it appears it is not possible to execute in it's current form on old versions of phpunit. The only thing is that I believe the `$this->afterApplicationCreated()` function is only available on laravel v5.2 and older.

https://github.com/tightenco/mailthief/blob/be93ed5362939707bb11fd483b870abb655a8557/src/Testing/InteractsWithMail.php#L57-L66

I'll submit a pull request to change it to detect if the `afterApplicationCreated()` function exists instead.

```php
    public function hijackMail()
    {
        if (method_exists($this, 'afterApplicationCreated')) {
            $this->afterApplicationCreated(function () {
                $this->getMailer()->hijack();
            });
        } else {
            $this->getMailer()->hijack();
        }
    }
```

**Pull request merged**
