### PR TITLE
Allow mailer to intercept Mailable objects

### PR DESCRIPTION
**Pull request by MarkVaughn**
in reference to #90
This lets mailthief intercept "Mailables"

note: My IDE sorted the imports and discarded the unused ones.

### CODE REVIEW

**Comment by benlarkins** [comment]
👍

**Comment by mattstauffer** [comment]
@MarkVaughn I have never used Mailthief and mailables in the same code base yet.

Would this allow you for testing the mailables' subjects, etc. like you described in #90? This seems too good to be true, but if this works, great! (I see it works in your test--just wanted to verify you've tried this on a real codebase.)

**Comment by MarkVaughn** [comment]
@mattstauffer like this https://github.com/tightenco/mailthief/pull/91/files#diff-7c30d7b10f5d1e5f153233b8584c2a36 ?

**Comment by mattstauffer** [comment]
@MarkVaughn right--I'm saying I see it working in the tests, but I want to see whether you've pulled Mailthief, with your changes in this PR, into an actual project and tested that the mailables work the way you want?

The code reads well (although my brain has not been in Mailthief space for a while) and you've gotten a thumbs up from @benlarkins; so those are quality signifiers for me. However, I haven't run this test on a local project and won't be able to for a bit, so I'm asking whether you have a personal project where you've tested this and seen whether it works the way you want.

Thanks!

**Comment by MarkVaughn** [comment]
OK, will do.

**Comment by mattstauffer** [comment]
@MarkVaughn Thanks for this! Sorry for the delay in testing and merging. :)

**Pull request merged**
