### PR TITLE
Mailables

### PR DESCRIPTION
**Pull request by spyric**
Mailables feature is presented in Laravel 5.3, but Mailthief is not support it. This PR makes easy to test emails with Mailables

### CODE REVIEW

**Comment by mattstauffer** [comment]
@spyric Thanks for this PR! I want to wait to merge this until 5.3 actually launches; mailables are still a bit in flux. Let's leave this PR, test it on 5.3 release day, and then merge it.

Thanks!

**Comment by calebporzio** [comment]
Announcement: we are undergoing a transition of maintainership. I will be taking over this project and going through the PRs in the coming days/weeks. Thanks for the patience and contributions, you should hear from me soon!

**Comment by m1guelpf** [comment]
@calebporzio "Soon"

**Comment by calebporzio** [comment]
For now, we aren't going to support Mailables in Mailthief because Laravel allows you to fake them out of the box.

**Pull request closed without merging**
